FROM oven/bun:1.3.11-alpine@sha256:7ed9f74c326d1c260abe247ac423ccbf5ac92af62bb442d515d1f92f21e8ea9b AS build

WORKDIR /opt/node_app

ARG BUILD_VERSION
ARG ARCHIVE_URL=https://github.com/excalidraw/excalidraw/archive/
ARG GIT_URL=https://github.com/excalidraw/excalidraw.git
#ARG NODE_ENV=production
#ARG NODE_OPTIONS=--openssl-legacy-provider

RUN test -n "${BUILD_VERSION}" \
    && apk update \
    && apk upgrade -a \
    && apk add --no-cache ca-certificates git \
    && update-ca-certificates \
    && git clone --depth 1 ${GIT_URL} .
    #&& git clone --depth 1 ${GIT_URL} . \
		#&& bun \
    #&& bun build:app:docker \
    #&& bun add cross-env react react-dom \
    #&& bun --cwd ./excalidraw-app build:app:docker

RUN bun install
RUN bun pm untrusted

ARG NODE_ENV=production

#RUN bun --cwd ./excalidraw-app run build:app:docker
RUN cd ./excalidraw-app && bun run build:app:docker


# ----------------------------------------------------------------------------



FROM nginx:1.29.8-alpine3.23@sha256:582c496ccf79d8aa6f8203a79d32aaf7ffd8b13362c60a701a2f9ac64886c93d

LABEL org.opencontainers.image.authors="Jauder Ho <jauderho@users.noreply.github.com>"
LABEL org.opencontainers.image.url="https://github.com/jauderho/dockerfiles"
LABEL org.opencontainers.image.documentation="https://github.com/jauderho/dockerfiles"
LABEL org.opencontainers.image.source="https://github.com/jauderho/dockerfiles"
LABEL org.opencontainers.image.title="jauderho/excalidraw"
LABEL org.opencontainers.image.description="Excalidraw is a virtual whiteboard for sketching hand-drawn like diagrams."

RUN apk update \
    && apk upgrade -a

#COPY --from=build /opt/node_app/build /usr/share/nginx/html
COPY --from=build /opt/node_app/excalidraw-app/build /usr/share/nginx/html

HEALTHCHECK CMD wget -q -O /dev/null http://localhost || exit 1
