FROM oven/bun:1.3.1-alpine@sha256:514fe15804f8ad3772ba323c2298daf121bb4b42386e2522998de5e87f16a94c AS build

WORKDIR /opt/node_app

ARG BUILD_VERSION
ARG ARCHIVE_URL=https://github.com/excalidraw/excalidraw/archive/
ARG GIT_URL=https://github.com/excalidraw/excalidraw.git
#ARG NODE_ENV=production
#ARG NODE_OPTIONS=--openssl-legacy-provider

RUN test -n "${BUILD_VERSION}" \
    && apk update \
    && apk upgrade -a \
    && apk add --no-cache ca-certificates git \
    && update-ca-certificates \
    && git clone --depth 1 ${GIT_URL} .
    #&& git clone --depth 1 ${GIT_URL} . \
		#&& bun \
    #&& bun build:app:docker \
    #&& bun add cross-env react react-dom \
    #&& bun --cwd ./excalidraw-app build:app:docker

RUN bun install
RUN bun pm untrusted

ARG NODE_ENV=production

#RUN bun --cwd ./excalidraw-app run build:app:docker
RUN cd ./excalidraw-app && bun run build:app:docker


# ----------------------------------------------------------------------------



FROM nginx:1.29.3-alpine3.22@sha256:b23ea6c10814fccb32ac20485c74168ebefa1c3544a3dddfcb33494d24270df8

LABEL org.opencontainers.image.authors="Jauder Ho <jauderho@users.noreply.github.com>"
LABEL org.opencontainers.image.url="https://github.com/jauderho/dockerfiles"
LABEL org.opencontainers.image.documentation="https://github.com/jauderho/dockerfiles"
LABEL org.opencontainers.image.source="https://github.com/jauderho/dockerfiles"
LABEL org.opencontainers.image.title="jauderho/excalidraw"
LABEL org.opencontainers.image.description="Excalidraw is a virtual whiteboard for sketching hand-drawn like diagrams."

RUN apk update \
    && apk upgrade -a

#COPY --from=build /opt/node_app/build /usr/share/nginx/html
COPY --from=build /opt/node_app/excalidraw-app/build /usr/share/nginx/html

HEALTHCHECK CMD wget -q -O /dev/null http://localhost || exit 1
