FROM oven/bun:1.1.34-alpine@sha256:490d28250f51bf30fd88c3277f43c2c2bd721599d9ae373458c487d27bcb10f3 AS build

WORKDIR /opt/node_app

ARG BUILD_VERSION
ARG ARCHIVE_URL=https://github.com/excalidraw/excalidraw/archive/
ARG GIT_URL=https://github.com/excalidraw/excalidraw.git
#ARG NODE_ENV=production
#ARG NODE_OPTIONS=--openssl-legacy-provider

RUN test -n "${BUILD_VERSION}" \
    && apk update \
    && apk upgrade -a \
    && apk add --no-cache ca-certificates git \
    && update-ca-certificates \
    && git clone --depth 1 ${GIT_URL} .
    #&& git clone --depth 1 ${GIT_URL} . \
		#&& bun \
    #&& bun build:app:docker \
    #&& bun add cross-env react react-dom \
    #&& bun --cwd ./excalidraw-app build:app:docker

RUN bun install
RUN bun pm untrusted

ARG NODE_ENV=production

#RUN bun --cwd ./excalidraw-app run build:app:docker
RUN cd ./excalidraw-app && bun run build:app:docker


# ----------------------------------------------------------------------------



FROM nginx:1.27.2-alpine3.20@sha256:74175cf34632e88c6cfe206897cbfe2d2fecf9bf033c40e7f9775a3689e8adc7

LABEL org.opencontainers.image.authors="Jauder Ho <jauderho@users.noreply.github.com>"
LABEL org.opencontainers.image.url="https://github.com/jauderho/dockerfiles"
LABEL org.opencontainers.image.documentation="https://github.com/jauderho/dockerfiles"
LABEL org.opencontainers.image.source="https://github.com/jauderho/dockerfiles"
LABEL org.opencontainers.image.title="jauderho/excalidraw"
LABEL org.opencontainers.image.description="Excalidraw is a virtual whiteboard for sketching hand-drawn like diagrams."

RUN apk update \
    && apk upgrade -a

#COPY --from=build /opt/node_app/build /usr/share/nginx/html
COPY --from=build /opt/node_app/excalidraw-app/build /usr/share/nginx/html

HEALTHCHECK CMD wget -q -O /dev/null http://localhost || exit 1
