name: Semgrep

on:
  pull_request: {}
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/semgrep.yml
  schedule:
  - cron: '0 0 * * 0'
  workflow_call:

permissions: read-all

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-26.04
    permissions:
      # Needed to upload the results to code-scanning dashboard.
      security-events: write
      actions: read
      contents: read      
    container:
      image: semgrep/semgrep:1.164.0@sha256:207983631beecdbe7fa29196c7f4a7a5f29033933cdb76c687ce4a672e07618d
    
    if: (github.actor != 'dependabot[bot]')
    
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
      with:
        egress-policy: block
        disable-telemetry: true
        allowed-endpoints: 
          github.com:443
          semgrep.dev:443
          
    - name: Checkout Code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        fetch-depth: 0
        persist-credentials: false    
        
    - run: semgrep scan --config auto
