name: Semgrep

on:
  pull_request: {}
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/semgrep.yml
  schedule:
  - cron: '0 0 * * 0'
  workflow_call:

permissions: read-all

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-24.04
    permissions:
      # Needed to upload the results to code-scanning dashboard.
      security-events: write
      actions: read
      contents: read      
    container:
      image: semgrep/semgrep
    
    if: (github.actor != 'dependabot[bot]')
    
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
      with:
        egress-policy: block
        disable-telemetry: true
        allowed-endpoints: 
          github.com:443
          semgrep.dev:443
          
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    
    - run: semgrep scan --config auto
